version: '3'
services:
  app:
    image: registry.fpfis.eu/comm/citizens/comm-citi-reference:0.30.0-development
    volumes:
      - .:/code
      - bundle:/usr/local/bundle

    environment:
      - PORT=3000
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/1
      - REDIS_CACHE_URL=redis://redis:6379/1
      - REDIS_SESSION_URL=redis://redis:6379/2
    ports:
      - 3000:3000
    links:
      - pg
    entrypoint: [ "./docker-entrypoint.sh" ]
    command: bundle exec ./bin/dev
  test:
    image: registry.fpfis.eu/comm/citizens/comm-citi-reference:0.30.0-test
    volumes:
      - .:/code
      - bundle:/usr/local/bundle

    environment:
      - PORT=3000
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=test
      - REDIS_URL=redis://redis:6379/1
      - REDIS_CACHE_URL=redis://redis:6379/1
      - REDIS_SESSION_URL=redis://redis:6379/2
    links:
      - pg
    entrypoint: [ "./docker-entrypoint.sh" ]
    command: bin/rails server
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis:latest
    ports:
      - 6379:6379
volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
